/*  =========================================================================
    fty_certificate_generator_classes - private header file

    Copyright (C) 2014 - 2020 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FTY_CERTIFICATE_GENERATOR_CLASSES_H_INCLUDED
#define FTY_CERTIFICATE_GENERATOR_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/fty-certificate-generator.h"

//  Opaque class structures to allow forward references
#ifndef CERTGEN_CERTIFICATE_GENERATOR_SERVER_T_DEFINED
typedef struct _certgen_certificate_generator_server_t certgen_certificate_generator_server_t;
#define CERTGEN_CERTIFICATE_GENERATOR_SERVER_T_DEFINED
#endif
#ifndef CERTGEN_CERTIFICATE_GENERATOR_CONFIG_T_DEFINED
typedef struct _certgen_certificate_generator_config_t certgen_certificate_generator_config_t;
#define CERTGEN_CERTIFICATE_GENERATOR_CONFIG_T_DEFINED
#endif
#ifndef CERTGEN_CERTIFICATE_CONFIG_T_DEFINED
typedef struct _certgen_certificate_config_t certgen_certificate_config_t;
#define CERTGEN_CERTIFICATE_CONFIG_T_DEFINED
#endif
#ifndef CERTGEN_KEY_CONFIG_T_DEFINED
typedef struct _certgen_key_config_t certgen_key_config_t;
#define CERTGEN_KEY_CONFIG_T_DEFINED
#endif
#ifndef CERTGEN_STORAGE_CONFIG_T_DEFINED
typedef struct _certgen_storage_config_t certgen_storage_config_t;
#define CERTGEN_STORAGE_CONFIG_T_DEFINED
#endif

//  Extra headers

//  Internal API

#include "certgen_certificate_generator_server.h"
#include "certgen_certificate_generator_config.h"
#include "certgen_certificate_config.h"
#include "certgen_key_config.h"
#include "certgen_storage_config.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef FTY_CERTIFICATE_GENERATOR_BUILD_DRAFT_API

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_CERTIFICATE_GENERATOR_PRIVATE void
    certgen_certificate_generator_server_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_CERTIFICATE_GENERATOR_PRIVATE void
    certgen_certificate_generator_config_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_CERTIFICATE_GENERATOR_PRIVATE void
    certgen_certificate_config_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_CERTIFICATE_GENERATOR_PRIVATE void
    certgen_key_config_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_CERTIFICATE_GENERATOR_PRIVATE void
    certgen_storage_config_test (bool verbose);

//  Self test for private classes
FTY_CERTIFICATE_GENERATOR_PRIVATE void
    fty_certificate_generator_private_selftest (bool verbose, const char *subtest);

#endif // FTY_CERTIFICATE_GENERATOR_BUILD_DRAFT_API

#endif
